Excavator: Manage go module dependencies

diff --git a/vendor/github.com/palantir/pkg/cobracli/godelw b/vendor/github.com/palantir/pkg/cobracli/godelw
--- a/vendor/github.com/palantir/pkg/cobracli/godelw
+++ b/vendor/github.com/palantir/pkg/cobracli/godelw
@@ -3,9 +3,11 @@
 set -euo pipefail
 
 # Version and checksums for godel. Values are populated by the godel "dist" task.
-VERSION=2.22.0
-DARWIN_CHECKSUM=b2bedf340419d79187643bf9a9dbdd0c4c46bccdcb597717b71dd165ac7129a7
-LINUX_CHECKSUM=25d36a20d33cba39d05f8a3c2c3768b3a02a3297f129308f3e2bc8c0951ba388
+VERSION=2.42.0
+DARWIN_AMD64_CHECKSUM=ab8bcc3b0f64e07f95d884805c0da28f18f96f1068c2818061c872896e85eb99
+DARWIN_ARM64_CHECKSUM=a9eeba295f6bc16ed0229c138dddb190aa9fa5c6d656baea2a14c01ab35bf70a
+LINUX_AMD64_CHECKSUM=aca1e86d07e8a015d0600a6139a857268724ac995e758d54fe89d34ce1d80e68
+LINUX_ARM64_CHECKSUM=e110dfdd54ca4a8bcfdc3fcd6b3dd9256920c084a21684b2eae5bdd5db28eec1
 
 # Downloads file at URL to destination path using wget or curl. Prints an error and exits if wget or curl is not present.
 function download {
@@ -108,7 +110,7 @@ function verify_dist_tgz_valid {
     local tgz_path=$1
     local version=$2
 
-    local expected_paths=("godel-$version/" "godel-$version/bin/darwin-amd64/godel" "godel-$version/bin/linux-amd64/godel" "godel-$version/wrapper/godelw" "godel-$version/wrapper/godel/config/")
+    local expected_paths=("godel-$version/" "godel-$version/bin/darwin-amd64/godel" "godel-$version/bin/darwin-arm64/godel" "godel-$version/bin/linux-amd64/godel" "godel-$version/bin/linux-arm64/godel" "godel-$version/wrapper/godelw" "godel-$version/wrapper/godel/config/")
     local files=($(tar -tf "$tgz_path"))
 
     # this is a double-for loop, but fine since $expected_paths is small and bash doesn't have good primitives for set/map/list manipulation
@@ -142,9 +144,10 @@ function verify_godel_version {
     local base_dir=$1
     local version=$2
     local os=$3
+    local arch=$4
 
     local expected_output="godel version $version"
-    local version_output=$($base_dir/godel-$version/bin/$os-amd64/godel version)
+    local version_output=$($base_dir/godel-$version/bin/$os-$arch/godel version)
 
     if [ "$expected_output" != "$version_output" ]; then
         echo "Version reported by godel executable did not match expected version: expected \"$expected_output\", was \"$version_output\""
@@ -161,23 +164,35 @@ GODEL_BASE_DIR=${GODEL_HOME:-$HOME/.godel}
 # determine OS
 OS=""
 EXPECTED_CHECKSUM=""
-case "$(uname)" in
-  Darwin*)
-    OS=darwin
-    EXPECTED_CHECKSUM=$DARWIN_CHECKSUM
-    ;;
-  Linux*)
-    OS=linux
-    EXPECTED_CHECKSUM=$LINUX_CHECKSUM
-    ;;
-  *)
-    echo "Unsupported operating system: $(uname)"
-    exit 1
-    ;;
+case "$(uname)-$(uname -m)" in
+    Darwin-x86_64)
+        OS=darwin
+        ARCH=amd64
+        EXPECTED_CHECKSUM=$DARWIN_AMD64_CHECKSUM
+        ;;
+    Darwin-arm64)
+        OS=darwin
+        ARCH=arm64
+        EXPECTED_CHECKSUM=$DARWIN_ARM64_CHECKSUM
+        ;;
+    Linux-x86_64)
+        OS=linux
+        ARCH=amd64
+        EXPECTED_CHECKSUM=$LINUX_AMD64_CHECKSUM
+        ;;
+    Linux-aarch64)
+        OS=linux
+        ARCH=arm64
+        EXPECTED_CHECKSUM=$LINUX_ARM64_CHECKSUM
+        ;;
+    *)
+        echo "Unsupported operating system-architecture: $(uname)-$(uname -m)"
+        exit 1
+        ;;
 esac
 
 # path to godel binary
-CMD=$GODEL_BASE_DIR/dists/godel-$VERSION/bin/$OS-amd64/godel
+CMD=$GODEL_BASE_DIR/dists/godel-$VERSION/bin/$OS-$ARCH/godel
 
 # godel binary is not present -- download distribution
 if [ ! -f "$CMD" ]; then
@@ -198,8 +213,11 @@ if [ ! -f "$CMD" ]; then
     mkdir -p "$GODEL_BASE_DIR/downloads"
 
     # download tgz and verify its contents
-    DOWNLOAD_DST=$GODEL_BASE_DIR/downloads/godel-$VERSION.tgz
+    # Download to unique location that includes PID ($$) and use trap ensure that temporary download file is cleaned up
+    # if script is terminated before the file is moved to its destination.
+    DOWNLOAD_DST=$GODEL_BASE_DIR/downloads/godel-$VERSION-$$.tgz
     download "$DOWNLOAD_URL" "$DOWNLOAD_DST"
+    trap 'rm -rf "$DOWNLOAD_DST"' EXIT
     if [ -n "$DOWNLOAD_CHECKSUM" ]; then
         verify_checksum "$DOWNLOAD_DST" "$DOWNLOAD_CHECKSUM"
     fi
@@ -209,11 +227,14 @@ if [ ! -f "$CMD" ]; then
     TMP_DIST_DIR=$(mktemp -d "$GODEL_BASE_DIR/tmp_XXXXXX" 2>/dev/null || mktemp -d -t "$GODEL_BASE_DIR/tmp_XXXXXX")
     trap 'rm -rf "$TMP_DIST_DIR"' EXIT
     tar zxvf "$DOWNLOAD_DST" -C "$TMP_DIST_DIR" >/dev/null 2>&1
-    verify_godel_version "$TMP_DIST_DIR" "$VERSION" "$OS"
+    verify_godel_version "$TMP_DIST_DIR" "$VERSION" "$OS" "$ARCH"
+
+    # rename downloaded file to remove PID portion
+    mv "$DOWNLOAD_DST" "$GODEL_BASE_DIR/downloads/godel-$VERSION.tgz"
 
     # if destination directory for distribution already exists, remove it
     if [ -d "$GODEL_BASE_DIR/dists/godel-$VERSION" ]; then
-          rm -rf "$GODEL_BASE_DIR/dists/godel-$VERSION"
+        rm -rf "$GODEL_BASE_DIR/dists/godel-$VERSION"
     fi
 
     # ensure that parent directory of destination exists
@@ -222,6 +243,17 @@ if [ ! -f "$CMD" ]; then
     # move expanded distribution directory to destination location. The location of the unarchived directory is known to
     # be in the same directory tree as the destination, so "mv" should always work.
     mv "$TMP_DIST_DIR/godel-$VERSION" "$GODEL_BASE_DIR/dists/godel-$VERSION"
+
+    # edge case cleanup: if the destination directory "$GODEL_BASE_DIR/dists/godel-$VERSION" was created prior to the
+    # "mv" operation above, then the move operation will move the source directory into the destination directory. In
+    # this case, remove the directory. It should always be safe to remove this directory because if the directory
+    # existed in the distribution and was non-empty, then the move operation would fail (because non-empty directories
+    # cannot be overwritten by mv). All distributions of a given version are also assumed to be identical. The only
+    # instance in which this would not work is if the distribution purposely contained an empty directory that matched
+    # the name "godel-$VERSION", and this is assumed to never be true.
+    if [ -d "$GODEL_BASE_DIR/dists/godel-$VERSION/godel-$VERSION" ]; then
+        rm -rf "$GODEL_BASE_DIR/dists/godel-$VERSION/godel-$VERSION"
+    fi
 fi
 
 verify_checksum "$CMD" "$EXPECTED_CHECKSUM"
